 # In-Class Programming Activity, Day 4

## Mira Ensley-Field

# Task 1: The frame

```{r}
plot(1, xlim = c(0, 100), ylim = c(0,100), type="n")

```


# Task 2
```{r}
plot(1, xlim = c(0, 100), ylim = c(0,100), type="n")
x1<-c(0,100,100,0)
y1<-c(0,0,100,100)

x2<-c(0,100,100,0,0)
y2<-c(0,0,100,100,0)

lines(x1, y1,pch=10,col="blue",cex=2)
lines(x2, y2,pch=10,col="red",cex=2)

```

# Task 3

```{r}
plot(1, xlim = c(0, 100), ylim = c(0,100), type="n")

angles<-seq(from = 0,to = 2*pi, by = pi/12)
x3<-50+20*sin(angles)
y3<-60+20*cos(angles)

lines(x3, y3,col="blue")


```

# Task 4
```{r}
plot(1, xlim = c(0, 100), ylim = c(0,100), type="n")


angles<-seq(from = 0,to = 2*pi, by = pi/12)
x4<-50+20*abs(sin(angles))*sin(angles)
y4<-60+20*abs(sin(angles))*cos(angles)

polygon(x4, y4,col="blue")

```


# Task 5: Bells and whistles

using color
using lwd
using pch
using xlab

```{r}
plot(1, xlim = c(0, 100), ylim = c(0,100), type="n", ylab= "color, lwd, pch, xlab, ylab", xlab = "Bells and Whistles"
     , xaxt="n",yaxt="n", main="Have a Nice Day!")


angles<-seq(from = 0,to = 2*pi, by = pi/12)
x5<-50+30*sin(angles)
y5<-50+40*cos(angles)

polygon(x5, y5,col="yellow")


angles2<-seq(from = pi/2, to = pi, by = pi/24)
x6<-40+30*sin(angles2)
y6<-50+20*cos(angles2)
lines(x6,y6,lwd=5)

x7<-c(40,60)
y7<-c(65,65)
points(x7,y7, pch=20, col="black",cex=6)


```




## Test statements

```{r}
scoreActivity::score253(4)
```