# In-Class Programming Activity, Day 5

# Mira Ensley-Field


Task 1-4
```{r,include=FALSE}
library(mosaic)
library(mosaicData)

```

```{r}

nbins<-10

evenly_spaced<-seq(min(Galton$height,data=Galton), max(Galton$height,data=Galton), length = nbins + 1)

bin_counts<-table(cut(Galton$height, breaks=evenly_spaced))

xL<-evenly_spaced[1:(length(evenly_spaced)-1)]
xR<-evenly_spaced[2:length(evenly_spaced)]
count<-as.numeric(bin_counts)
hist_basics<-data.frame(xL,xR,count)

```


Task 5

```{r}
make_one_bar <- function(point) {
  xLeft <- point$xL
  xRight <- point$xR
  height <- point$count
  res <- data.frame(
              x = c(xLeft,  xLeft,  xRight, xRight, NA),
              y = c(    0, height,  height,      0, NA)
  )
  res
}

one_to_five <- function(hist_data) {
  bars <- NULL
  for (k in 1:nrow(hist_data)) {
    new_bar <- make_one_bar(hist_data[k, ])
    bars <- rbind(bars, new_bar)
  }
  bars
}
```

Task 6
Draw the histogram.
```{r}

My_bars<-(one_to_five(hist_basics))
plot(My_bars,type="n")
lines(My_bars)
polygon(My_bars,col="Blue")
```


## Test statements

```{r}
scoreActivity::score253(5)
```