# In-Class Programming Activity, Day 6

#Task 1

```{r,results="hide",include=FALSE}
library(mosaic)
library(mosaicData)
nbins<-10
```

#Task 1: myHistogram and Normal curve
```{r}

make_one_bar <- function(point) {
  xLeft <- point$xL
  xRight <- point$xR
  height <- point$count
  res <- data.frame(
              x = c(xLeft,  xLeft,  xRight, xRight, NA),
              y = c(    0, height,  height,      0, NA)
  )
  res
}

one_to_five <- function(hist_data) {
  bars <- NULL
  for (k in 1:nrow(hist_data)) {
    new_bar <- make_one_bar(hist_data[k, ])
    bars <- rbind(bars, new_bar)
  }
  bars
}

myHistogram<-function(v,nbins, color,fill) {
  #Histogram
  evenly_spaced<-seq(min(v), max(v), length = nbins + 1)
  bin_counts<-table(cut(v, breaks=evenly_spaced))

  xL<-evenly_spaced[1:(length(evenly_spaced)-1)]
  xR<-evenly_spaced[2:length(evenly_spaced)]
  count<-as.numeric(bin_counts)
  hist_basics<-data.frame(xL,xR,count)

  My_bars<-(one_to_five(hist_basics))
  plot(My_bars,type="n")
  lines(My_bars)
  polygon(My_bars,col=color, fillOddEven =fill)
  
  
  # Normal Curve
  x <- seq(min(v),max(v),length=1000)
  normal <- dnorm(x,mean(v),sd(v))

  #Together
  par(new=TRUE)
  plot(x,normal)
  
  return(invisible(bin_counts))

}
```

Task1 test
```{r}
myHistogram(v=Galton$height,nbins=10,color="green",fill=TRUE)
```

# Task 2

```{r}
datax <- c(runif(10, 1, 2), runif(20, 4,6))
datav <- rnorm(10, mean=100, sd=1)
bw<-(diff(range(datax))/sqrt(length(datax)))

kernel<-function(x,y) dnorm(x,mean=y,sd=bw)

gridx <- seq(0,10, length = 200) 

M <- outer(gridx, datax, FUN = kernel)
dens <- rowSums(M)

```


#Task 2 different dataset
```{r}
datax <- c(runif(10, 1, 2), runif(20, 4,6))
v <- rnorm(100, mean=100, sd=1)

bw<-(diff(range(datax))/sqrt(length(datax)))

kernel<-function(x,y) dnorm(x,mean=y,sd=bw)
 
gridx <- seq(0,10, length = 200) 
gridV<-seq(95,105,length=50)

M <- outer(gridx, datax, FUN = kernel)
N<- outer(gridV,v,FUN=kernel)

dens <- rowSums(M)

densN<-rowSums(N)
plot(gridV,densN)

plot(gridx, dens)

```



#Task 3


```{r}
plotdensity<-function(v,xlim=NULL){
  bw<-function(v){(diff(range(v))/sqrt(length(v)))}
  kernel<-function(x,y){dnorm(x,mean=y,sd=bw(x))}
  
  #Create grid
  start<-min(v)-bw(v)
  end<-max(v)+bw(v)
#  if(xlim.isNull){
#    xlim<-length(v)
#  }
  gridV<-seq(start,end,length=length(v))

  M<-outer(gridV,v,FUN=kernel)
  dens<-rowSums(M)
  dframe<-data.frame(gridV,dens)
  plot(gridV,dens)
  return(invisible(dframe))

}
```

Testing Task 3
```{r}
plotdensity(datax)
```

## Test statements

```{r}
scoreActivity::score253(6)
```